### PR TITLE
fix name conflict with Arduino/Time.h

### PR DESCRIPTION
**Pull request by dpeddi**
Hi,

I'm using Eclipse + Sloeber.io under Windows environment.

It seems that your Time.h conflict with include\time.h

Please can you consider to rename the Time.cpp and Time.h to something else like proposed with this pull request?

Regards

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
This was fixed in November 2015
https://github.com/PaulStoffregen/Time/commit/26cd0c85095d5dbfffded0831abb2f7abaad0469

Use TimeLib.h, not Time.h.  Open any of the examples for any example!

**Comment by PaulStoffregen** [comment]
Why did you reopen this?

**Comment by dpeddi** [comment]
Sure!

This time i've tried with platformio...

As an example I took your TimeSerial.ino  and ESP_AsyncFSBrowser.ino (from ESPAsyncWebServer)

I merged them... 


Build fails as follow:

lib\ESPAsyncWebServer\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(tm*)':
lib\ESPAsyncWebServer\src\WebHandlers.cpp:67:64: error: 'strftime' was not declared in this scope
strftime (result,30,"%a, %d %b %Y %H:%M:%S %Z", last_modified);
^
lib\ESPAsyncWebServer\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(time_t)':
lib\ESPAsyncWebServer\src\WebHandlers.cpp:72:60: error: 'gmtime' was not declared in this scope
return setLastModified((struct tm *)gmtime(&last_modified));
^
lib\ESPAsyncWebServer\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified()':
lib\ESPAsyncWebServer\src\WebHandlers.cpp:77:25: error: 'time' was not declared in this scope
if(time(&last_modified) == 0) //time is not yet set
^
*** [.pioenvs\nodemcuv2\lib\ESPAsyncWebServer\WebHandlers.o] Error 1
 [ERROR] Took 13.84 seconds

On build directory I have
Time.o 

so gcc take your Time.o when I've requested for time.o... 
Probably due to Windows case insensitive file system!

So including TimeLib.h seems not enough both with Eclipse and PlatformIO

**Comment by dpeddi** [comment]
Hi,

Have you been able to replicate the issue?

**Comment by PaulStoffregen** [comment]
Report this problem on platformio, **NOT** here!

DO NOT REOPEN this issue.  If it works on Arduino, do not report the issue here.

**Comment by vshymanskyy** [comment]
I really vote for removing `Time.h`.

**Comment by richard-scott** [comment]
@PaulStoffregen - Please could you release v1.6 from your master branch?

The changes you have made to use TimeLib.h instead of Time.h are not being used by PlatformIO users as you've not told them to use the latest codebase. I get version 1.5 of your Time library when adding it as a project dependency.

Likewise, any other project that depends on this Lib installs the old (v1.5) version.

**Comment by richard-scott** [comment]
Actually don't worry, I'm using the [ezTime ](https://github.com/ropg/ezTime) library now.

**Comment by PaulStoffregen** [comment]
> Please could you release v1.6 from your master branch?

Done.  https://github.com/PaulStoffregen/Time/releases/tag/v1.6

**Pull request closed without merging**
